### ISSUE TITLE
How do I even explain this?

### ISSUE THREAD

**Issue by ajdudex014** [xJon/The-1.7.10-Pack#1096]
Most vanilla block textures for no reason have minions or emojis, etc. and I didn't even download a resourcepack. What is going on and how do I fix it?

**Comment by Scottvrakis** [comment]
Seconded, I cannot for the life of me find out what happened, I have a couple of screenshots for reference. 

Could this be due to the newest update and fix? This is really weird... Even some sounds like receiving fall damage has been altered. I've uploaded the images to [imgur](http://imgur.com/a/OvOIw) in order to prevent a huge post.

**Comment by xJon** [comment]
:trollface:
