### ISSUE TITLE
Unexpected Crash

### ISSUE THREAD

**Issue by Excepto** [xJon/The-1.7.10-Pack#1137]
Trying to load a world I created earlier. as far as i could see it had something to do with ticking block

**Comment by Excepto** [comment]
[techniclauncher_2016-05-20.txt](https://github.com/xJon/The-1.7.10-Pack/files/274875/techniclauncher_2016-05-20.txt)

**Comment by xJon** [comment]
We're using the latest version of Buildctaft, so this should be reported [there](https://github.com/BuildCraft/BuildCraft/issues).
As for fixing your issue, you'll have to manually delete the ticking block entity using [NBTExplorer](https://www.youtube.com/watch?v=fWUUsdp3pJ8).

**Comment by AlexIIL** [comment]
Hi, BuildCraft dev here.

This is caused by *a* mod adding a recipe to the recipe list while the server is running (from a different thread) and that causes the recipe iteration to fail (as the list was modified from a different thread). So not something that we can fix, and it will crop up in other mods auto-crafting functions as well. The issue is with the mod that added the recipe, although I don't know all of the mods you are running so I can't help you with which mod is actually causing the issue.

**Comment by xJon** [comment]
Interesting. I can't think about such mod that adds custom recipes in the pack.
@Excepto Did you add any new mods manually?

**Comment by Excepto** [comment]
Nope I didn't. I was using auto crafting tables for crafting compressed cobble and dirt from extra utilities

**Comment by xJon** [comment]
Unfortunately I have no idea which mod causes that.
