### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by CoolerSide** [xJon/The-1.7.10-Pack#1206]
When i started singleplayer or join to server i got this problem "a fatal error has occurred this connection is terminated". Please help.

**Comment by Curunir** [comment]
Imagine somebody told you on the phone that their dog had vomited, and then asked you what disease the dog might have and how to cure it. What is your answer?
Your problem is pretty much the same, except that the server vomited, not the dog. We know nothing of your computer, your installed programs, the way may or may not have installed the pack correctly, and least of all what might have gone wrong. The absolute minimum you need to do is share a damn crash log with us, because there may be some things in there that could give us a clue. With the one-liner you gave us, I'll just say the dog has cancer and will die before sunset.

**Comment by mandm635** [comment]
Make sure you are using the same version of the modpack as the server. The server may not have updated yet. You can usually find what version they are using on their website(if it's a public server).

**Comment by ciak2009** [comment]
If you read the ticket he does state it happens in single player too, so that would not be the issue.

**Comment by ciak2009** [comment]
Accidentally closed.

**Comment by xJon** [comment]
Closed due to missing information. Will reopen with the required info (`fml-client-latest.log`).
