### ISSUE TITLE
My World Won't Load

### ISSUE THREAD

**Issue by Dominatr1113** [xJon/The-1.7.10-Pack#1212]
Whenever I try to load up my single-player world, it seems like it will load fine but then very shortly after opening the world, the screen turns white and won't load. I'm looking for anybody that can solve this problem for me. Thank you.

**Comment by xJon** [comment]
Please post your `fml-client-log.latest` file using a [paste-tool](http://paste.ubuntu.com/).

**Comment by spacemonkey** [comment]
Same here but I can't paste that file from here (blocked access to paste sites). Essentially a pre-existing world loaded (with all the magical crops 3 stuff gone of course) but twice I created new worlds which crashed immediately upon creating.

Actually one world managed to load, I was flying around in creative and must have stumbled upon a biome/thing that made it crash. Will upload logs when I can.

**Comment by xJon** [comment]
@spacemonkey Still waiting for logs!

**Comment by xJon** [comment]
Still waiting for logs

**Comment by spacemonkey** [comment]
@xJon Ended up deleting everything (even the pack) and starting all over again, so far so good...

I think the issue is with something from a previous version of the mod not getting cleared (something that spawns on the surface, as my world crashed while flying around looking for specific biomes).

On a slightly related but not really note - I also smacked a zombie pigman into the portal to send him back to the nether and that completely killed one world (in the previous release of the modpack). Not sure if that was just bad luck on my part, or me showing my true merit as the ultimate testing machine ;-)

**Comment by xJon** [comment]
Well? That's modded Minecraft I guess. Open a new issue if you can understand directly what's the problem.
