### ISSUE TITLE
modded mincraft technic launchar pack 1.7.10 crash

### ISSUE THREAD

**Issue by doilohr** [xJon/The-1.7.10-Pack#1243]
trying to join the recommended server for the pack and it crashes have been playing on it for a few weeks and now today it doesn't work today i loaded it up and then i tp,d into a storage room with thaumcraft and me systems that me and a bud had been working on i have 7 gigs of ram allocated to the pack and a 6 core processor and a GTX 960 usually get around 120 fps here is the crash report
http://pastebin.com/yStWu2YM

**Comment by oryfoxer7410** [comment]
There are some known issues with some mods using outdated API's for RF. This can be seen here. https://forum.feed-the-beast.com/threads/2-3-3-2-3-5-infinity-evolved-ender-io-crash.140326/

This error was reported back in January. Since the server isn't crashing on you loading your chunk, do you know if anyone else is able to load the area? 

If its just you crashing on the chunk load, you should try completely deleting your pack and reinstalling. If everyone crashes on load, you should report this to who owns the server and have them remove the erroring items.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if needed.
