### ISSUE TITLE
Mod Suggestions

### ISSUE THREAD

**Issue by OrmcoZpak** [xJon/The-1.7.10-Pack#1245]
Hello,

I currently own a server our group of friends with the 1.7.10 pack running on it and have added additional mods to it. I feel they should be in the pack already!
## 

**Decocraft**
https://minecraft.curseforge.com/projects/decocraft2
This mod is a must for those who love to decorate.

**Plant** **Mega** **Pack**
http://minecraftsix.com/plant-mega-pack-mod/
Minecraft feels very barren. This mod helps bring a lot more lushness to the map.

**Traincraft**
https://minecraft.curseforge.com/projects/traincraft
To be completely honest... I delete railcraft entirely and replace it with this vastly surperior, gorgeous train mod.

**Better** **Foliage**
https://minecraft.curseforge.com/projects/better-foliage
Again, Minecraft feels barren... and dull. Along with Plant Mega Pack, this adds more lushness and life to the world.

**Mo'** **Creatures**
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1272337-mo-creatures-v10-0-0
Adds new mobs to your game, it provides many new animal and monster mobs, as well as the ability to tame, breed, and ride some.

**Comment by Curunir** [comment]
Concerning Mo'Creatures and probably also the Plant Mega Pack, these are very heavy and will add undue weight to an already huge pack. Many users are struggling with the pack as it is, and we would rather not break their game completely by adding these.

Traincraft for Railcraft might be a thing, but with a large playerbase invested in the status quo, we would rather not break everybody's railways without a very good reason. It might be best to formulate a poll on it. Jon will do that if he thinks the idea has merit. Don't badger him about it, though.

Better Foliage does do nice things for Minecraft, but it will also tax players' machines more heavily. Since it is a client-side mod entirely, you can always just add it to your local installation, and you should still be able to connect to regular The 1.7.10 Pack servers. Don't blame us for bad fps, though.

I still have nothing to say for or against Decocraft.

**Comment by xJon** [comment]
@Curunir Summed everything up very precisely. Decocraft is already in different suggestions so I'm closing this one.
