### ISSUE TITLE
Suggestion: Remove Mystcraft and add Draconic Evolution and RFtools.

### ISSUE THREAD

**Issue by kingstinger1** [xJon/The-1.7.10-Pack#1278]
What the title says ;)

I know Mystcraft isnt compatible with RFtools but its a crap mod anyways and likes to over load servers with zillions of dimensions. The mod is usually banned on servers anyways because of this.

**Comment by Curunir** [comment]
I actually agree with your assessment. The sooner we get rid of Mystcraft, the better. RFTools is more useful, server-friendly and fun to use in any way. However, there are two downsides:
1. Mystcraft is magic-themed (or more precisely, Myst-themed), while RFTools is a tech-themed mod. The change might be grating to people who like their dimensions to be scribbled by magical ink instead of cold, hard technology. Also, RFTools dimensions require a constant power supply to keep running, which might further alienate the magic crowd.
2. We have a large playerbase invested in Mystcraft dimensions, even with many servers disabling it. If we made the change, all these people would lose all their existing Mystcraft dimensions, including all that is inside them. This is a drastic step that would require general consensus among a majority of the playerbase. Any good ideas how to create that consensus? Me neither.

**Comment by kingstinger1** [comment]
Draconic evolution and rf tools would require world gen. There for would be
an effective change on world reset.

**Comment by xJon** [comment]
@Curunir said it perfectly.
Thanks anyway for suggesting.
