### ISSUE TITLE
Uncrafting watering can

### ISSUE THREAD

**Issue by RobinEH** [xJon/The-1.7.10-Pack#1291]
When using the Uncrafting Table from The Twilight Forest to uncraft a Watering Can (Reinforced) from Extra Utilities the items for a regular watering can is given back. Could this be fixed? They use the same name ExtraUtilities:watering_can but the ID differs from 5931 to 5931:3.

**Comment by Curunir** [comment]
Thank you for pointing it out, but it probably can't be fixed. Mod interaction failures like this are hell to debug, and usually the individual mod authors don't think it's even an issue. Use the Uncrafting Table with care in general, because it will likely have many more such bugs.
I'll leave this open in case Jon wants to comment yet, but don't expect a solution.
