### ISSUE TITLE
Server download 0.9.5 Broken?

### ISSUE THREAD

**Issue by Tyler13700** [xJon/The-1.7.10-Pack#1316]
It contains 211 mods, meanwhile the recommended server (with a check) has 217. I can't join due to this, and I'm wondering if the pack updated and the server download didn't?

**Comment by xJon** [comment]
What? Both the server packages have the same amount of files inside of their `/mods/` folder. Also the server packages are always being tested before they are being uploaded. Please check if the issue is on your end

**Comment by xJon** [comment]
Is this still an issue?

**Comment by Curunir** [comment]
The number of mods is actually not definitive when you compare the number of JAR files and number of mods reported by Forge. That is because some mods actually count as more than one.
If you try to connect to a server and there is mod mismatch, that is either because you are not running the same pack version as the server does, or because either the server or your client has been altered.

**Comment by Tyler13700** [comment]
I simply reverted back to 0.9.4 and that seemed to work fine. The main problem is, when my friend tries to connect with Hamachi, he either times out of gets a java error. The server, only having about 1GB ram, Is super laggy and refuses to generate chunks sometimes, along with the random timing out too.

**Comment by ramorga** [comment]
You need to run the modpack with at least 3 GB of RAM.  Otherwise, you will experience crashes and lag.

**Comment by Tyler13700** [comment]
Im not sure how to allocate more RAM to my server.

**Comment by xJon** [comment]
Closed due to inactivity.
For other problems, open new specific issues.
