### ISSUE TITLE
1.7.10 Pack Server Not Starting

### ISSUE THREAD

**Issue by fruitypigy** [xJon/The-1.7.10-Pack#1341]
I recently installed the 1.7.10 pack onto technic and wanted to play with friends. I installed the 1.7.10 pack from technic and I'm not able to run the server. It opens loads for a while then gives me an error message at the end which I believe is the issue:
[12:40:33] [Server thread/INFO] [FML/]: The state engine was in incorrect state ERRORED and forced into state SERVER_STOPPED. Errors may have been discarded.
[12:40:33] [Server thread/INFO] [FML/]: The state engine was in incorrect state ERRORED and forced into state AVAILABLE. Errors may have been discarded.

I agreed to the eula, gave it 5 gigs of ram and am running 64 bit java
Here is the full log

[fml-server-.txt](https://github.com/xJon/The-1.7.10-Pack/files/768768/fml-server-.txt)

**Comment by Curunir** [comment]
Did it also generate a crash log? Because I cannot see anything wrong there - it looks like the server just randomly got into this error state, without any reason. You are using the correct Java version and everything else I can see there looks normal.
Did you try to just re-run it and see if it happens again?

**Comment by fruitypigy** [comment]
Ha ha
I had been doing it over and over but as soon as I put this up it worked again
:p 
Thanks Anyways
