### ISSUE TITLE
Server won't allow mod items to be crafted

### ISSUE THREAD

**Issue by TandT89** [xJon/The-1.7.10-Pack#1430]
I'm having problems running a server for my friend and I. Neither of us can craft anything that isn't from Vanilla minecraft. I thought I read somewhere that increasing the amount of memory would help, but it didn't.

I would post logs, but I don't know how; Help would be appreciated

**Comment by Curunir** [comment]
That is because you are running a vanilla Minecraft server. For obvious reasons, modpacks have to include the vanilla jarfile, but you are supposed to start the server using the script, and only the script. You instead started the jarfile, and the wrong one at that.
Better trash your existing world and start over. It will have no modded content whatsoever.
