### ISSUE TITLE
Pack server crashing

### ISSUE THREAD

**Issue by kdonley** [xJon/The-1.7.10-Pack#1458]
Server worked fine for a week and now its getting this error:

**EDITED BY JON: Please use a paste tool - https://pastebin.com/y0tRZwsa**

**Comment by Azamorn666** [comment]
According to this:
https://stackoverflow.com/questions/20777884/com-google-gson-jsonprimitive-cannot-be-cast-to-com-google-gson-jsonobject-error
It seems that there is an issue in the Pneumaticcraft config json files, I'd check that out, try copy pasting them in a json validator to see where the issue is.

**Comment by gogobebe2** [comment]
@Azamorn666 Did you ever end up resolving this issue?

**Comment by kdonley** [comment]
No, I just have to restore a backup whenever it happens which is about once
a week

**Comment by xJon** [comment]
Try to reset PneumaticCraft's config files.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
