### ISSUE TITLE
Help setting up a server without lag

### ISSUE THREAD

**Issue by thederpmachine** [xJon/The-1.7.10-Pack#1496]
Currently, I'm hosting a server on a desktop with an i7 4770, 16G RAM and a GTX 760. I have 12 GB of ram dedicated to the server, but it's still extremely laggy, the average tick spikes to over 500 ms sometimes(Combat is basically unplayable). Is there something I can do to help with the lag, or do I need a more powerful system?

**Comment by xJon** [comment]
You can try using a different launch server file, try using this line:
`java -server -Xmx%mem% -XX:PermSize=256M -XX:+UseG1GC -Xms4G -Dsun.rmi.dgc.server.gcInterval=2147483646 -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -Dfml.queryResult=confirm -jar forge-1.7.10-10.13.4.1614-1.7.10-universal.jar nogui`

**Comment by thederpmachine** [comment]
Doesn't seem to have changed much, do you want me to send you the server log file? (Also my client lag kinda fixed itself, so you can delete my other thread)

**Comment by xJon** [comment]
Yes, sure

**Comment by thederpmachine** [comment]
https://paste.ubuntu.com/p/VsBywTNdHc/

**Comment by xJon** [comment]
It actually doesn't show that the server is skipping any ticks due to server lag, so the lag has to be client-sided. You shouldn't dedicate so much RAM into your server, 3-4 GB would do fine, and then you'd have more RAM for your client (but still don't allocate more than 4-5 GB). That should fix your problem.
