### ISSUE TITLE
Nether biomes in overworld

### ISSUE THREAD

**Issue by Gabriel2536** [xJon/The-1.7.10-Pack#1510]
Hello,

I came across an issue, where nether biomes spawn in the overworld. From what I could find on the internet, it could be Biomes'o'planty corruption due to some conflicting ids? I'm sure some would be happy to have nether mobs spawn in the overworld, but not me, when I started to build a 100x100 desert temple, only to find out, that I have about 10 small patches of corrupted sands biomes scattered just around the build with Ghasts spawning left and right destroying the build while trying to hit me.
I play on a server with a friend so I disabled mob griefing at least. I know, there's nothing that would fix this map, but if somehow fixing this issue could help others prevent this I would be happy.
Oh, and the desert looks normal, just at some places the description changes to the corrupted desert (no out of place looking stuff or anything).

**Comment by xJon** [comment]
What modpack version are you playing?

**Comment by Gabriel2536** [comment]
I started the map at 0.9.7 and currently playing at 0.9.8, but the biomes definitely spawned at 0.9.7.

**Comment by xJon** [comment]
Phew okay. There were known biome conflicts in v0.9.7 and they were fixed in v0.9.8.
A quick way to check whether this particular biome mismatch is fixed is to go to the mismatched nether biomes in the overworld and check what's the *current* biome name, in v0.9.8. If it's not a nether biome's name but an overworld biome's name, it's fixed.
Anyway, if more mismatched biomes are generated with v0.9.8 please report them too.

**Comment by xJon** [comment]
Any update?

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen with the required info.
