### ISSUE TITLE
Fatally Missing Blocks and Items

### ISSUE THREAD

**Issue by Lightning793** [xJon/The-1.7.10-Pack#1683]
I've had a server running for a few days, but only ran into this error today.  I was just playing on the server and it crashed. Tried to start the server again and log back in and got this "Fatally missing blocks and items." Then started a new server and used a backup which went fine for almost an hour, but the server crashed again and the same thing happened.

Crash report:
[crash-2019-02-12_20.34.50-server.txt](https://github.com/xJon/The-1.7.10-Pack/files/2858509/crash-2019-02-12_20.34.50-server.txt)

Really have no idea what's going on so any help would be appreciated!

**Comment by Lightning793** [comment]
Also having trouble with the backups. Tried to load a recent backup when I created the server the 2nd time but it could locate the file. Had to use a backup from the beginning of that day to start the server again.

**Comment by Lightning793** [comment]
https://paste.ubuntu.com/p/mn8wQ5WD4Q/

**Comment by xJon** [comment]
With the crash log you've supplied, the issue seems like corrupted chunks, but the other crashes could be for different reasons. Also you have to make sure to close the server properly to allow the game to save and therefore avoid corrupted chunks. 

* One solution would be to restore a world backup (although it seems like you're aware of this).
* A second solution would be trying to use [Region Fixer](https://github.com/Fenixin/Minecraft-Region-Fixer).
* You can also try to delete\replace the corrupted chunk with a backup, as it seems to be region (0,-1)


Good luck!

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if required.
