### ISSUE TITLE
The state engine was in incorrect state SERVER_STOPPING and forced into state SERVER_STOPPED. Errors may have been discarded.

### ISSUE THREAD

**Issue by Sonocs** [xJon/The-1.7.10-Pack#1697]
PC crashed on me, so sudden server shutdown, hasn't worked since then.
https://paste.ubuntu.com/p/PXhdhVGYCq/

**Comment by xJon** [comment]
You simply have corrupted questing data - simply reset (delete) the inside of `HardcoreQuesting` within your server's world folder. This will reset your quests progress, but you can always cheat the items you had back in if you want.

**Comment by aniimu** [comment]
I have the same problem but with another errorr


[21:09:33] [Server thread/INFO] [FML]: The state engine was in incorrect state **ERRORED** and forced into state SERVER_STOPPED. Errors may have been discarded.

[21:09:33] [Server thread/INFO] [FML]: The state engine was in incorrect state **ERRORED** and forced into state AVAILABLE. Errors may have been discarded.

This is the first strart whit this server/modpack and i have no [HardcoreQuesting] ore world folder

i only started the Launchserver.sh [Because Linux is installed] and then this is happens. 

I have no clue how to fix this

**Comment by xJon** [comment]
@aniimu Make sure `eula.txt.` is set to true or open your own issue and post the full log using a paste-tool.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if required.

**Comment by godshanks99** [comment]
@xJon you said this : "You simply have corrupted questing data - simply reset (delete) the inside of HardcoreQuesting within your server's world folder. This will reset your quests progress, but you can always cheat the items you had back in if you want."
and i dont know were to find the HardcoreQuesting im in the world forlder and idk were to click

**Comment by xJon** [comment]
> @xJon you said this : "You simply have corrupted questing data - simply reset (delete) the inside of HardcoreQuesting within your server's world folder. This will reset your quests progress, but you can always cheat the items you had back in if you want."
> and i dont know were to find the HardcoreQuesting im in the world forlder and idk were to click

It is inside the world save folder, another folder called `HardcoreQuesting`.
