### ISSUE TITLE
Server started to crash never did before.

### ISSUE THREAD

**Issue by Genericikea** [xJon/The-1.7.10-Pack#1702]
I am running on The 1.7.10 Pack Server 0.9.8b it just started to crash also tried The 1.7.10 Pack Server 0.9.8 same thing 
https://paste.ubuntu.com/p/Q6rRSmzwSH/

**Comment by xJon** [comment]
1. If you're crashing due to a problematic block or entity, you can try setting these two settings to true in `the-1710-pack\configs\forge.cfg` **after you've backed up your save**:
```
    # Set this to true to remove any Entity that throws an error in its update method instead of closing the server and reporting a crash log. BE WARNED THIS COULD SCREW UP EVERYTHING USE SPARINGLY WE ARE NOT RESPONSIBLE FOR DAMAGES.
    B:removeErroringEntities=true

    # Set this to true to remove any TileEntity that throws an error in its update method instead of closing the server and reporting a crash log. BE WARNED THIS COULD SCREW UP EVERYTHING USE SPARINGLY WE ARE NOT RESPONSIBLE FOR DAMAGES.
    B:removeErroringTileEntities=true
```
2. If this does not work still you can try to manually use NBTExplorer as seen in [this tutorial](https://www.youtube.com/watch?v=fWUUsdp3pJ8).
3. Lastly you can consider using one of the auto backups the modpack creates.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if required.
