### ISSUE TITLE
Pressing "O" in options.

### ISSUE THREAD

**Issue by Jamiecoolcat** [xJon/The-1.7.10-Pack#1714]
Whenever I try to get to the Options menu for Ichuns stuff, it opens the search bar for the controls, any ways to fix this?

**Comment by xJon** [comment]
It seems like the issue is caused by the Controlling mod, added in version v0.9.8b to allow searching controls and listing conflicting controls.
The workaround would be changing these iChun settings & controls through the config files of each mod and the `iChunUtil_KeyBinds.cfg` file.
Alternatively you can remove the Controlling mod.
