### ISSUE TITLE
Client Crash upon startup

### ISSUE THREAD

**Issue by Justoffurmama** [xJon/The-1.7.10-Pack#1889]
As title says I cannot load into my world because as soon as I spawn in the world I instantly crash. I do not know what I can do to fix it.

[crash-2020-01-15_21.20.41-server.txt](https://github.com/xJon/The-1.7.10-Pack/files/4074914/crash-2020-01-15_21.20.41-server.txt)

[crash-2020-01-15_21.09.24-client.txt](https://github.com/xJon/The-1.7.10-Pack/files/4074915/crash-2020-01-15_21.09.24-client.txt)

Hopefully I am at the right place to find answers.

**Comment by xJon** [comment]
Please post your logs using a [paste-tool](https://pastebin.com/).

**Comment by Justoffurmama** [comment]
https://pastebin.com/Fmc3tQu0 
Im not sure if this is what you wanted. If I was supposed to do it a different way let me know

**Comment by Justoffurmama** [comment]
https://pastebin.com/5xV3kdQ0 the client

**Comment by xJon** [comment]
1. If you're crashing due to a problematic block or entity, you can try setting these two settings to true in `configs\forge.cfg` **after you've backed up your save**:
```
    # Set this to true to remove any Entity that throws an error in its update method instead of closing the server and reporting a crash log. BE WARNED THIS COULD SCREW UP EVERYTHING USE SPARINGLY WE ARE NOT RESPONSIBLE FOR DAMAGES.
    B:removeErroringEntities=true

    # Set this to true to remove any TileEntity that throws an error in its update method instead of closing the server and reporting a crash log. BE WARNED THIS COULD SCREW UP EVERYTHING USE SPARINGLY WE ARE NOT RESPONSIBLE FOR DAMAGES.
    B:removeErroringTileEntities=true
```
2. If this doesn't solve the issue you can try to remove the problematic's block/entity's mod and therefor delete all of its content from your save, which might help solve the problem.
3. If this does not work still you can try to manually use NBTExplorer as seen in [this tutorial](https://www.youtube.com/watch?v=fWUUsdp3pJ8).

**Comment by Justoffurmama** [comment]
Seems like the first option worked. Thank you!
