### ISSUE TITLE
Crash upon entering World (Loading NBT Data Error)

### ISSUE THREAD

**Issue by SlightlyDecent02** [xJon/The-1.7.10-Pack#1916]
Recently, a world in which I and some friends had played on problemlessly for weeks has now corrupted without explanation. A buddy of mine has recently given me the files to the server, and I am attempting to find a solution. (They have the backups and are I have alerted them of this possible solution)

The world appears to crash the instant I am spawned in, reaching the ESC Menu briefly and then instantly being kicked back to the technic home screen for the pack. I checked the crash reports, and this is what was given.

https://pastebin.com/k7UaAXAt

Would deleting ChickenChunks solve this issue, or is something more sinister going on?

Edit: My friend uninstalled/reinstalled the pack, thus deleting the backups. RIP

**Comment by xJon** [comment]
If you were given the files to the server, can't you load a backup?

**Comment by SlightlyDecent02** [comment]
I was given the save only, not any of the content is the backups file.

**Comment by xJon** [comment]
Unfortunately it seems that your world is corrupted.
1. If you're crashing due to a problematic block or entity, you can try setting these two settings to true in `the-1710-pack\config\forge.cfg` after you've backed up your save:
```
    # Set this to true to remove any Entity that throws an error in its update method instead of closing the server and reporting a crash log. BE WARNED THIS COULD SCREW UP EVERYTHING USE SPARINGLY WE ARE NOT RESPONSIBLE FOR DAMAGES.
    B:removeErroringEntities=true

    # Set this to true to remove any TileEntity that throws an error in its update method instead of closing the server and reporting a crash log. BE WARNED THIS COULD SCREW UP EVERYTHING USE SPARINGLY WE ARE NOT RESPONSIBLE FOR DAMAGES.
    B:removeErroringTileEntities=true
```
2. A second solution would be trying to use [Region Fixer](https://github.com/Fenixin/Minecraft-Region-Fixer).
3. If this does not work still you can try to manually use NBTExplorer as seen in [this tutorial](https://www.youtube.com/watch?v=fWUUsdp3pJ8), although I see that in your crash log there is no specification for the problematic block/chunk, unfortunately.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
