### ISSUE TITLE
search bar problem

### ISSUE THREAD

**Issue by FiTzLab1** [xJon/The-1.7.10-Pack#1960]
I cant look at recipes or search up items in the search bar when I'm in my inventory, and when I search stuff the letters show up red

**Comment by Jaari** [comment]
Did you double-click on the search bar by chance?

**Comment by FiTzLab1** [comment]
![2022-01-16_01 21 06](https://user-images.githubusercontent.com/18255601/149651301-d74d2caf-a162-4488-a7ea-0a9f0758f890.png)
![2022-01-16_01 21 08](https://user-images.githubusercontent.com/18255601/149651302-90d8b8c1-f6ea-4ae8-b47b-cab328551108.png)

**Comment by FiTzLab1** [comment]
Ive tried double clicking it(second picture) it didnt work, theres no items on the right side of the screen, theres no items to click on to see the recipe and when I search up Flans it doesnt show up and the words are in red

**Comment by xJon** [comment]
I looked into this and it seems this is caused due to a dependency incompatibility with the new version of NEI we're using (by GTNH). The dependencies shipped with the modpack were mismatching, which was usually resolved automatically by the mod with an internet connection, but is not ideal.
This was patched for `0.10.4`, so @FiTzLab1 if you can please try to reinstall the modpack through the launcher, let me know if you can see the items again in NEI!

**Comment by FiTzLab1** [comment]
Thank you, redownloading it fixed it
